### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by rafaelsdellama** [arthurfortes/consulta_correios#1]
address = consulta_correios.busca_cep('04509905')

Traceback (most recent call last):
  File "/home/user/darf_generator/venv/bin/darf_generator-cli", line 11, in <module>
    load_entry_point('DARF-Generator', 'console_scripts', 'darf_generator-cli')()
  File "/home/user/darf_generator/darf_generator/darf_generator_cli.py", line 63, in main
    address = consulta_correios.busca_cep(row[5])
  File "/home/user/darf_generator/venv/lib/python3.7/site-packages/consulta_correios/correios_api.py", line 38, in busca_cep
    'address': unidecode.unidecode(re.sub(' - .*', '', info[0].string).strip()),
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by arthurfortes** [comment]
Hi, @rafaelsdellama ! 

Sorry for what happened and thanks for the report. 

I fixed the code and already updated the repository and the pypi. Please use:

`pip install -U Consulta-Correios
`
to get the latest version or pull the repository.
