### ISSUE TITLE
TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by Edamas** [arthurfortes/consulta_correios#3]
endereco = 'Rua Itaiteva, Jardim Ampliação, São Paulo/SP'
consulta_correios.busca_cep(endereco)

RESULT:

---------------------------------------------------------------------------
TooManyRedirects                          Traceback (most recent call last)
<ipython-input-310-80a843210544> in <module>
      1 logradouro = 'Rua Itaiteva, Jardim Ampliação, São Paulo/SP'
      2 print(logradouro)
----> 3 consulta_correios.busca_cep(logradouro)

C:\ProgramData\Anaconda3\lib\site-packages\consulta_correios\correios_api.py in busca_cep(data_info)
     22             }
     23 
---> 24     r = session.post(
     25         "http://www.buscacep.correios.com.br/sistemas/buscacep/resultadoBuscaCepEndereco.cfm", data)
     26 

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in post(self, url, data, json, **kwargs)
    576         """
    577 
--> 578         return self.request('POST', url, data=data, json=json, **kwargs)
    579 
    580     def put(self, url, data=None, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         }
    529         send_kwargs.update(settings)
--> 530         resp = self.send(prep, **send_kwargs)
    531 
    532         return resp

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    663             # Redirect resolving generator.
    664             gen = self.resolve_redirects(r, request, **kwargs)
--> 665             history = [resp for resp in gen]
    666         else:
    667             history = []

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in <listcomp>(.0)
    663             # Redirect resolving generator.
    664             gen = self.resolve_redirects(r, request, **kwargs)
--> 665             history = [resp for resp in gen]
    666         else:
    667             history = []

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    164 
    165             if len(resp.history) >= self.max_redirects:
--> 166                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
    167 
    168             # Release the connection back into the pool.

TooManyRedirects: Exceeded 30 redirects.

**Comment by MarkBone** [comment]
ERRO: 

>>> cep = consulta_correios.busca_cep('80420-010')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Desktop\DJANGO\project\venv\lib\site-packages\consulta_correios\correios_api.py", line 24, in busca_cep
    r = session.post(
  File "C:\Users\Desktop\DJANGO\project\venv\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Desktop\DJANGO\project\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Desktop\DJANGO\project\venv\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\Desktop\DJANGO\project\venv\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\Desktop\DJANGO\project\venv\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
>>>

**Comment by marcomeireles39** [comment]
sou novo aqui no github menos de 2 semanas porem já postei em meu repositorio um porjeto que busca o endereço só pelo cpf

agora que entrei aqui vi este projeto gostei muito parabens ao desenvolvedor
